import "server-only";
import { PNG } from "pngjs";
import ImageTracer, { type ImageTracerOptions, type ImageTracerPaletteColor, type ImageTracerTraceData } from "imagetracerjs";
import type { IconGenerationParams } from "@/lib/supabase/types";
import { normalizeIconSvg } from "@/lib/svg/normalize";

/**
 * Raster -> SVG vectorization for icons generated by the OpenAI image model.
 *
 * Deliberately NOT "ask an LLM to trace/clean up the SVG": tracing is a
 * well-defined geometric operation (classify each pixel to the nearest of a
 * few known flat colors, then fit vector paths to each color region), and a
 * classic bitmap tracer does it exactly and deterministically. We give
 * ImageTracer our own literal 2-3 color palette (pure black / mid-gray /
 * white) and colorquantcycles=1 so it classifies pixels against those exact
 * colors instead of "discovering" a palette from the image — that keeps the
 * output colors perfectly predictable, so remapping them to `currentColor`
 * afterwards is a simple, exact string match rather than a fuzzy nearest-color
 * guess.
 */

const BACKGROUND_COLOR: ImageTracerPaletteColor = { r: 255, g: 255, b: 255, a: 255 };
const PRIMARY_COLOR: ImageTracerPaletteColor = { r: 0, g: 0, b: 0, a: 255 };
const SECONDARY_COLOR: ImageTracerPaletteColor = { r: 140, g: 140, b: 140, a: 255 };
const SECONDARY_OPACITY = 0.28;

function paletteForStyle(style: IconGenerationParams["style"]): ImageTracerPaletteColor[] {
  return style === "duotone"
    ? [PRIMARY_COLOR, SECONDARY_COLOR, BACKGROUND_COLOR]
    : [PRIMARY_COLOR, BACKGROUND_COLOR];
}

function sameColor(a: ImageTracerPaletteColor, b: ImageTracerPaletteColor): boolean {
  return a.r === b.r && a.g === b.g && a.b === b.b;
}

function decodePng(buffer: Buffer): { width: number; height: number; data: Buffer } {
  const png = PNG.sync.read(buffer);
  return { width: png.width, height: png.height, data: png.data };
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function rgbString(c: ImageTracerPaletteColor): string {
  return `rgb(${c.r},${c.g},${c.b})`;
}

/**
 * ImageTracer's tosvgcolorstr() always emits exactly:
 *   fill="rgb(r,g,b)" stroke="rgb(r,g,b)" stroke-width="0" opacity="1"
 * for one of our fully-opaque literal palette colors (we set strokewidth:0).
 * We match that exact, predictable substring and replace it with a plain
 * currentColor fill — no stroke, no redundant opacity="1" clutter.
 */
function remapColorToCurrentColor(svg: string, color: ImageTracerPaletteColor, opacity?: number): string {
  const rgb = escapeRegExp(rgbString(color));
  const pattern = new RegExp(`fill="${rgb}" stroke="${rgb}" stroke-width="0" opacity="1" `, "g");
  const replacement = opacity !== undefined ? `fill="currentColor" fill-opacity="${opacity}" ` : `fill="currentColor" `;
  return svg.replace(pattern, replacement);
}

function cleanupTracedSvg(svg: string, style: IconGenerationParams["style"]): string {
  let result = svg.replace(/\s+version="1\.1"/, "").replace(/\s+desc="[^"]*"/, "");

  result = remapColorToCurrentColor(result, PRIMARY_COLOR);
  if (style === "duotone") {
    result = remapColorToCurrentColor(result, SECONDARY_COLOR, SECONDARY_OPACITY);
  }

  return normalizeIconSvg(result);
}

export function vectorizeIconImage(
  png: Buffer,
  params: Pick<IconGenerationParams, "canvasSize" | "style">
): string {
  const image = decodePng(png);
  const palette = paletteForStyle(params.style);
  const scale = params.canvasSize / image.width;

  const options: ImageTracerOptions = {
    pal: palette,
    colorsampling: 0,
    numberofcolors: palette.length,
    colorquantcycles: 1, // keep our literal palette colors as-is, no averaging drift
    mincolorratio: 0,
    layering: 0,
    // pathomit/ltres/qtres scale with source resolution so tuning survives a
    // change to SOURCE_SIZE in lib/ai/openai.ts.
    pathomit: Math.round(image.width * 0.012),
    ltres: Math.max(1, image.width * 0.006),
    qtres: Math.max(1, image.width * 0.006),
    rightangleenhance: false,
    blurradius: 2,
    blurdelta: 20,
    strokewidth: 0,
    linefilter: true,
    scale,
    roundcoords: 2,
    viewbox: true,
    desc: false,
  };

  const tracedata = ImageTracer.imagedataToTracedata(
    { width: image.width, height: image.height, data: image.data },
    options
  );

  const kept = tracedata.palette
    .map((color, index) => ({ color, index }))
    .filter(({ color }) => !sameColor(color, BACKGROUND_COLOR));

  if (kept.every(({ index }) => tracedata.layers[index].length === 0)) {
    throw new Error("הוקטוריזציה לא הפיקה צורות (ייתכן שהתמונה ריקה או שקופה לגמרי).");
  }

  const filtered: ImageTracerTraceData = {
    ...tracedata,
    palette: kept.map(({ color }) => color),
    layers: kept.map(({ index }) => tracedata.layers[index]),
  };

  const rawSvg = ImageTracer.getsvgstring(filtered, options);
  return cleanupTracedSvg(rawSvg, params.style);
}
